name: pinterest_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: ^0.13.4
  logger: ^1.1.0
  simple_animations: ^4.0.1
  cached_network_image: ^3.2.0
  flutter_staggered_grid_view: ^0.6.1
  permission_handler: ^9.2.0
  fluttertoast: ^8.0.8
  share_plus: ^3.1.0
  dio: ^4.0.4
  image_picker: ^0.8.4+9
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/locals/
    - assets/images/icons/
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

